config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :animals

      resources :animal_types
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "animal_types#index"
  resources :animals
  resources :animal_types
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  mount_base64_uploader :photo, PhotoUploader

  # Direct associations

  belongs_to :animal_type

  # Indirect associations

  # Validations

  validates :age, numericality: { greater_than_or_equal_to: 0 }

  # Scopes

  def to_s
    animal_type.to_s
  end
end

app/models/animal_type.rb
class AnimalType < ApplicationRecord
  # Direct associations

  has_many   :animals,
             dependent: :destroy

  # Indirect associations

  # Validations

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animal_types_controller.rb
class AnimalTypesController < ApplicationController
  before_action :set_animal_type, only: %i[show edit update destroy]

  def index
    @q = AnimalType.ransack(params[:q])
    @animal_types = @q.result(distinct: true).includes(:animals).page(params[:page]).per(10)
  end

  def show
    @animal = Animal.new
  end

  def new
    @animal_type = AnimalType.new
  end

  def edit; end

  def create
    @animal_type = AnimalType.new(animal_type_params)

    if @animal_type.save
      redirect_to @animal_type, notice: "Animal type was successfully created."
    else
      render :new
    end
  end

  def update
    if @animal_type.update(animal_type_params)
      redirect_to @animal_type, notice: "Animal type was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @animal_type.destroy
    redirect_to animal_types_url,
                notice: "Animal type was successfully destroyed."
  end

  private

  def set_animal_type
    @animal_type = AnimalType.find(params[:id])
  end

  def animal_type_params
    params.require(:animal_type).permit(:name, :description)
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[show edit update destroy]

  def index
    @q = Animal.ransack(params[:q])
    @animals = @q.result(distinct: true).includes(:animal_type).page(params[:page]).per(10)
  end

  def show; end

  def new
    @animal = Animal.new
  end

  def edit; end

  def create
    @animal = Animal.new(animal_params)

    if @animal.save
      message = "Animal was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @animal, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @animal.update(animal_params)
      redirect_to @animal, notice: "Animal was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @animal.destroy
    message = "Animal was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to animals_url, notice: message
    end
  end

  private

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:animal_type_id, :photo, :name,
                                   :description, :age)
  end
end

app/controllers/api/v1/animal_types_controller.rb
class Api::V1::AnimalTypesController < Api::V1::GraphitiController
  def index
    animal_types = AnimalTypeResource.all(params)
    respond_with(animal_types)
  end

  def show
    animal_type = AnimalTypeResource.find(params)
    respond_with(animal_type)
  end

  def create
    animal_type = AnimalTypeResource.build(params)

    if animal_type.save
      render jsonapi: animal_type, status: :created
    else
      render jsonapi_errors: animal_type
    end
  end

  def update
    animal_type = AnimalTypeResource.find(params)

    if animal_type.update_attributes
      render jsonapi: animal_type
    else
      render jsonapi_errors: animal_type
    end
  end

  def destroy
    animal_type = AnimalTypeResource.find(params)

    if animal_type.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: animal_type
    end
  end
end

app/controllers/api/v1/animals_controller.rb
class Api::V1::AnimalsController < Api::V1::GraphitiController
  def index
    animals = AnimalResource.all(params)
    respond_with(animals)
  end

  def show
    animal = AnimalResource.find(params)
    respond_with(animal)
  end

  def create
    animal = AnimalResource.build(params)

    if animal.save
      render jsonapi: animal, status: :created
    else
      render jsonapi_errors: animal
    end
  end

  def update
    animal = AnimalResource.find(params)

    if animal.update_attributes
      render jsonapi: animal
    else
      render jsonapi_errors: animal
    end
  end

  def destroy
    animal = AnimalResource.find(params)

    if animal.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: animal
    end
  end
end

app/controllers/api/v1/graphiti_controller.rb
class Api::V1::GraphitiController < ApplicationController
  include Graphiti::Rails::Responders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collapse_search_form
    if params[:q].blank?
      "collapse"
    else
      ""
    end
  end

  def link_to_show_or_back(
    object,
        show_content = "Show",
        back_content = "Back",
        options = {}
  )
    if request.path == url_for(object)
      link_to back_content, :back, options
    else
      link_to show_content, object, options
    end
  end
end

app/views/animal_types/_animal_type_animals.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Animals

    <a data-toggle="collapse" href="#animal_type_animals_new_form">
      Add animal
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @animal_type.animals.each do |animal| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to animal, animal %>

        <%= link_to animal, method: :delete, data: { confirm: "Do you really want to delete this animal" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="animal_type_animals_new_form">
        <%= render partial: "animal_types/animal_type_animals_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/animal_types/_animal_type_animals_new_form.html.erb
<%= form_with(model: @animal, local: true) do |f| %>

  <%= f.hidden_field :animal_type_id, value: @animal_type.id %>

  <div class="form-group">
    <%= f.label :photo %>

    <%= f.file_field :photo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>

    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :age %>

    <%= f.text_field :age, class: "form-control" %>
  </div>

  <%= f.submit "Create animal", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/animal_types/_animal_types_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "animal_types_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/animal_types" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#animal_types_filters">
  Show filters
</a>

app/views/animal_types/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Animal Type #<%= animal_type.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= animal_type.name %></dd>

      <dt>Description</dt>
      <dd><%= animal_type.description %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back animal_type, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_animal_type_url(animal_type), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to animal_type, method: :delete, data: { confirm: "Do you really want to delete this animal_type?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(animal_type.updated_at) %> ago
  </div>
</div>

app/views/animal_types/_form.html.erb
<% was_validated = animal_type.errors.any? %>

<%= form_with(model: animal_type, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = animal_type.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% animal_type.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = animal_type.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_field :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% animal_type.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/animal_types/_list_item.html.erb
<%= link_to animal_type, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= animal_type %>
    <small class="text-muted">
      <%= time_ago_in_words(animal_type.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/animal_types/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Animal Type #<%= @animal_type.id %>
      </h2>

      <div class="card-body">
        <%= render "form", animal_type: @animal_type %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animal_types/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Animal Types

      <%= link_to new_animal_type_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "animal_types/animal_types_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Animal Types

        <%= link_to new_animal_type_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @animal_types, partial: "list_item", as: :animal_type %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @animal_types, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/animal_types/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Animal Type
      </h2>

      <div class="card-body">
        <%= render "form", animal_type: @animal_type %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animal_types/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @animal_type, partial: "card", as: :animal_type %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "animal_types/animal_type_animals" %>
  </div>
</div>

app/views/animals/_animals_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "animals_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :age, "Age" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :age_gteq, :class => "form-control", :placeholder => "Age greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :age_lteq, :class => "form-control", :placeholder => "Age less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :animal_type_name_cont, "Animal type name contains" %>
    <%= f.text_field :animal_type_name_cont, :class => "form-control", :placeholder => "Animal type name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/animals" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#animals_filters">
  Show filters
</a>

app/views/animals/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Animal #<%= animal.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Animal type</dt>
      <dd>
        <% if @animal.animal_type.present? %>
          <%= link_to animal.animal_type, animal.animal_type %>
        <% end %>
      </dd>

      <dt>Photo</dt>
      <dd>
        <%= cl_image_tag @animal.photo, class: "img-fluid" %>
      </dd>

      <dt>Name</dt>
      <dd><%= animal.name %></dd>

      <dt>Description</dt>
      <dd><%= animal.description %></dd>

      <dt>Age</dt>
      <dd><%= animal.age %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back animal, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_animal_url(animal), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to animal, method: :delete, data: { confirm: "Do you really want to delete this animal?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(animal.updated_at) %> ago
  </div>
</div>

app/views/animals/_form.html.erb
<% was_validated = animal.errors.any? %>

<%= form_with(model: animal, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% animal_type_class = "form-control" %>
    <% animal_type_was_invalid = animal.errors.include?(:animal_type) %>

    <% if was_validated %>
      <% if animal_type_was_invalid %>
        <% animal_type_class << " is-invalid" %>
      <% else %>
        <% animal_type_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :animal_type_id %>
    <%= f.collection_select :animal_type_id, AnimalType.all, :id, :to_s, {}, class: "form-control" %>
    <% if animal_type_was_invalid %>
      <% animal.errors.full_messages_for(:animal_type).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% photo_class = "form-control" %>
    <% photo_was_invalid = animal.errors.include?(:photo) %>

    <% if was_validated %>
      <% if photo_was_invalid %>
        <% photo_class << " is-invalid" %>
      <% else %>
        <% photo_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control" %>
    <% if photo_was_invalid %>
      <% animal.errors.full_messages_for(:photo).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = animal.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% animal.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = animal.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_field :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% animal.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% age_class = "form-control" %>
    <% age_was_invalid = animal.errors.include?(:age) %>

    <% if was_validated %>
      <% if age_was_invalid %>
        <% age_class << " is-invalid" %>
      <% else %>
        <% age_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :age %>
    <%= f.number_field :age, class: age_class, placeholder: "Enter age" %>
    <% if age_was_invalid %>
      <% animal.errors.full_messages_for(:age).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/animals/_list_item.html.erb
<%= link_to animal, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= animal %>
    <small class="text-muted">
      <%= time_ago_in_words(animal.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/animals/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Animal #<%= @animal.id %>
      </h2>

      <div class="card-body">
        <%= render "form", animal: @animal %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animals/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Animals

      <%= link_to new_animal_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "animals/animals_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Animals

        <%= link_to new_animal_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @animals, partial: "list_item", as: :animal %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @animals, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/animals/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Animal
      </h2>

      <div class="card-body">
        <%= render "form", animal: @animal %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @animal, partial: "card", as: :animal %>
  </div>
</div>

app/views/shared/_bootstrapcdn_assets.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" >

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>